services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html:ro
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm7.4 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 2
      start_period: 30s
  static_website:
    build: ./requirements/bonus/static_website
    container_name: static_website
    networks:
      - inception
    restart: always
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception
networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/asajed/data/wp'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/asajed/data/db'
