events {}

http {
    server {
        listen 80;
        server_name 84.8.216.175 inception.aymanesajed.com asajed.42.fr;

        return 301 https://inception.aymanesajed.com$request_uri;
    }
    server {
        listen 443 ssl;
        server_name 84.8.216.175;

        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        return 301 https://inception.aymanesajed.com$request_uri;
    }
    server {
        listen 443 ssl;
        server_name inception.aymanesajed.com asajed.42.fr;

        root /var/www/html;
        index index.php index.html;

        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location /static_website/ {
            proxy_pass http://static_website:80/;
            proxy_set_header Host $host;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_index index.php;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}